### PR TITLE
Ah.site reporting

### LINKED ISSUE #225: Implement route: Report site for issues
**Why**
- Users should be able to report a site to admins if they spot an issue with it, such as an inappropriate name or incorrect data

**What to do**
- See [the API spec of this route](https://docs.c4cneu.com/sftt/sftt-api-spec/#report-site-for-issues) for more details
- The route should send an email to SFTT admins containing the issue info from the request, along with the reporter's name and email
  - i.e. the admin should know who reported what site for what reason
  - See [this PR](https://github.com/Code-4-Community/speak-for-the-trees-backend-v2/pull/222/files#diff-f9a1ffb387d61e400cbab6f7e2773fbe6a130acc5a5e5918e9615129fc4f984c) for an example of how to send emails (specifically `ProtectedSiteProcessorImpl` and `Emailer`)
  - Create a new template to send to admins
- Add a new environment variable for the destination email address for reports
  - See `deploy.py`, `.github/workflows/deploy.yml`, and [this PR](https://github.com/Code-4-Community/speak-for-the-trees-backend-v2/commit/ab813ad0ad7556673f77bfa4e32cf8f27dbdf6d8#diff-41f62c787888bcd1955045260a58df9ad5323d9c92c33802f8230eacd07452c3) as a guide for loading env vars - don't hesitate to reach out to Avery if you have questions here since it can get pretty opaque

### PR DESCRIPTION
**Pull request by huang0h**
## Why

Resolves #225 

Users should have a way to report sites for any problems they find, e.g. incorrect data displayed on the site or inappropriate content (names, images)

## This PR

- Implements the report site route mentioned in the ticket
  - non-admins are limited to 15 reports a day to avoid people from spamming SFTT
- Adds a new email template for report emails to be sent to SFTT

## Verification Steps

- Verified the email sent with the correct contents to the correct address (sample at bottom)
- Verified that users are prevented from making reports if they have 15+ reports within 24 hours
- Verified admins can make reports even if they have 15+ reports within 24 hours

unnamed

### CODE REVIEW

File: service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java [hunk 1]
```diff
@@ -230,6 +239,22 @@ private void checkCanUploadImage(JWTData userData) throws AuthException {
...
+    int reportsToday = db.selectCount()
+        .from(USER_SITE_REPORTS)
+        .where(USER_SITE_REPORTS.USER_ID.eq(userData.getUserId()))
+        .and(USER_SITE_REPORTS.CREATED_AT.greaterOrEqual(Timestamp.valueOf(LocalDateTime.now().minusDays(1))))
+        .fetchOne(0, int.class);
+
+    if (reportsToday >= MAX_DAILY_SITE_REPORTS) {
+      throw new ForbiddenException("Users can only make " + MAX_DAILY_SITE_REPORTS + " reports a day!");
+    }
+  }
```
Comment (CerberusLatrans) [inline service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java:256]: nice logic

File: common/src/main/resources/emails/SiteIssueReport.html [hunk 2]
```diff
@@ -0,0 +1,394 @@
...
+                                    </table>
+                                    <![endif]-->
+                                    <!--[if mso]>
+                                    <table style="width: 100%; border-collapse: collapse; border: 0">
+                                        <tr>
+                                            <td style="padding: 10px 30px; font-family: Tahoma, sans-serif">
+                                    <![endif]-->
+                                    <div style="color:#555555;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;line-height:1.5; padding: 10px 30px">
+                                        <div style="line-height: 1.5; font-size: 15px; text-align: center; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #808389; mso-line-height-alt: 18px;">
+                                                ${name} (${email}) found the following issue with <a href="${siteLink}" target="_blank">site ${siteId}</a>: <b>${reportReason}</b>.
```
Comment (CerberusLatrans) [inline common/src/main/resources/emails/SiteIssueReport.html:206]: Just curious-- how did you get the siteLink variable here? I don't see it being passed with the templateValues hash map but in your screenshot I assume that it works and links to that site's page?

**Review by CerberusLatrans — APPROVED** [review]

File: persist/src/main/resources/db/migration/V6__AddUserReports.sql
[the remark this answers is not in the document]
Comment (CerberusLatrans) [reply persist/src/main/resources/db/migration/V6__AddUserReports.sql:1]: just to confirm

[the remark this answers is not in the document]
Comment (huang0h) [reply persist/src/main/resources/db/migration/V6__AddUserReports.sql:1]: Yeah, my intention is basically to just track the reports people make for that reason. If we want to in the future, we could definitely add reason and description if want to track what kinds of reports people are making

File: common/src/main/resources/emails/SiteIssueReport.html (hunk 2 above)
Comment (huang0h) [reply common/src/main/resources/emails/SiteIssueReport.html:206]: Good catch! I'm actually not passing `siteLink` in at all, so the link is broken. I didn't actually test the link and just assumed it worked, so that's my bad here.

**Comment by huang0h** [comment]
Moved the site report destination env variable out of `system.properties.example` to avoid people accidentally sending emails to SFTT when testing - you'll have to manually set this yourself to your own email.

**Review by CerberusLatrans — APPROVED** [review]
good looking to me!
